volumes:
  flowise-mat:

networks:
  demo-mat:

services:
   flowise:
    build:
      context: ./flowise
      dockerfile: Dockerfile
    networks: ['demo-mat']
    restart: unless-stopped
    container_name: flowise-mat
    ports:
    - "3001:3001"
    extra_hosts:
    - "host.docker.internal:host-gateway"
    volumes:
    - flowise-mat:/app/backend/data
