volumes:
  open-webui-mat:

networks:
  demo-mat:

services:
   open-webui:
    build:
      context: ./open-webui
      dockerfile: Dockerfile
    networks: ['demo-mat']
    restart: unless-stopped
    container_name: open-webui-mat
    ports:
    - "3000:8080"
    extra_hosts:
    - "host.docker.internal:host-gateway"
    volumes:
    - open-webui-mat:/app/backend/data
